package music2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.03 14:01:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi75 */
  @Test
  public void testRekisteroi75() {    // Kappale: 75
    Kappale kappale1 = new Kappale(); 
    assertEquals("From: Kappale line: 77", 0, kappale1.getTunnusNro()); 
    kappale1.rekisteroi(); 
    Kappale kappale2 = new Kappale(); 
    kappale2.rekisteroi(); 
    int n1 = kappale1.getTunnusNro(); 
    int n2 = kappale2.getTunnusNro(); 
    assertEquals("From: Kappale line: 83", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta123 */
  @Test
  public void testAseta123() {    // Kappale: 123
    Kappale kappale = new Kappale(); 
    assertEquals("From: Kappale line: 125", null, kappale.aseta(1,"Alex Pervukhin")); 
    assertEquals("From: Kappale line: 126", null, kappale.aseta(2,"This for B")); 
    assertEquals("From: Kappale line: 127", null, kappale.aseta(3,"Vinyl")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone204 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone204() throws CloneNotSupportedException {    // Kappale: 204
    Kappale kappale = new Kappale(); 
    kappale.parse("   3  |  Alex Pervukhin   | This For B"); 
    Kappale kopio = kappale.clone(); 
    assertEquals("From: Kappale line: 209", kappale.toString(), kopio.toString()); 
    kappale.parse("   4  |  artisti2  | biisi1"); 
    assertEquals("From: Kappale line: 211", false, kopio.toString().equals(kappale.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals227 */
  @Test
  public void testEquals227() {    // Kappale: 227
    Kappale kappale1 = new Kappale(); 
    kappale1.parse("   3  |  Alex   | This For B"); 
    Kappale kappale2 = new Kappale(); 
    kappale2.parse("   3  |  Alex   | This For B"); 
    Kappale kappale3 = new Kappale(); 
    kappale3.parse("   3  |  Alex   | Juuu"); 
    assertEquals("From: Kappale line: 235", true, kappale1.equals(kappale2)); 
    assertEquals("From: Kappale line: 236", true, kappale2.equals(kappale1)); 
    assertEquals("From: Kappale line: 237", false, kappale1.equals(kappale3)); 
    assertEquals("From: Kappale line: 238", false, kappale3.equals(kappale2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString287 */
  @Test
  public void testToString287() {    // Kappale: 287
    Kappale kappale = new Kappale(); 
    kappale.parse("   3  |  Alex   | This For B"); 
    assertEquals("From: Kappale line: 290", true, kappale.toString().startsWith("3|Alex|This For B|"));  // on enemm‰kin kuin 3 kentt‰‰, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse333 */
  @Test
  public void testParse333() {    // Kappale: 333
    Kappale kappale = new Kappale(); 
    kappale.parse("   3  |  Guy From Downstairs   | Nokia"); 
    assertEquals("From: Kappale line: 336", 3, kappale.getTunnusNro()); 
    assertEquals("From: Kappale line: 337", true, kappale.toString().startsWith("3|Guy From Downstairs|Nokia|"));  // on enemm‰kin kuin 3 kentt‰‰, siksi loppu |
    kappale.rekisteroi(); 
    int n = kappale.getTunnusNro(); 
    kappale.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    kappale.rekisteroi();  // ja tarkistetaan ett‰ seuraavalla kertaa tulee yht‰ isompi
    assertEquals("From: Kappale line: 343", n+20+1, kappale.getTunnusNro()); 
  } // Generated by ComTest END
}