package music2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.28 12:23:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa32() throws SailoException {    // Kappaleet: 32
    Kappaleet kappaleet = new Kappaleet(); 
    Kappale kappale1 = new Kappale(), kappale2 = new Kappale(); 
    assertEquals("From: Kappaleet line: 36", 0, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 37", 1, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale2); assertEquals("From: Kappaleet line: 38", 2, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 39", 3, kappaleet.getLkm()); 
    assertEquals("From: Kappaleet line: 40", kappale1, kappaleet.anna(0)); 
    assertEquals("From: Kappaleet line: 41", kappale2, kappaleet.anna(1)); 
    assertEquals("From: Kappaleet line: 42", kappale1, kappaleet.anna(2)); 
    assertEquals("From: Kappaleet line: 43", false, kappaleet.anna(1) == kappale1); 
    assertEquals("From: Kappaleet line: 44", true, kappaleet.anna(1) == kappale2); 
    try {
    assertEquals("From: Kappaleet line: 45", kappale1, kappaleet.anna(3)); 
    fail("Kappaleet: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 46", 4, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 47", 5, kappaleet.getLkm()); 
    try {
    kappaleet.lisaa(kappale1); 
    fail("Kappaleet: 48 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}