package music2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.21 12:14:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KappaleetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa59 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa59() throws SailoException {    // Kappaleet: 59
    Kappaleet kappaleet = new Kappaleet(); 
    Kappale kappale1 = new Kappale(), kappale2 = new Kappale(); 
    assertEquals("From: Kappaleet line: 63", 0, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 64", 1, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale2); assertEquals("From: Kappaleet line: 65", 2, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 66", 3, kappaleet.getLkm()); 
    assertEquals("From: Kappaleet line: 67", kappale1, kappaleet.anna(0)); 
    assertEquals("From: Kappaleet line: 68", kappale2, kappaleet.anna(1)); 
    assertEquals("From: Kappaleet line: 69", kappale1, kappaleet.anna(2)); 
    assertEquals("From: Kappaleet line: 70", false, kappaleet.anna(1) == kappale1); 
    assertEquals("From: Kappaleet line: 71", true, kappaleet.anna(1) == kappale2); 
    try {
    assertEquals("From: Kappaleet line: 72", kappale1, kappaleet.anna(3)); 
    fail("Kappaleet: 72 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 73", 4, kappaleet.getLkm()); 
    kappaleet.lisaa(kappale1); assertEquals("From: Kappaleet line: 74", 5, kappaleet.getLkm()); 
    try {
    kappaleet.lisaa(kappale1); 
    fail("Kappaleet: 75 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}