package music2.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.19 22:55:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RelaatiotTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa58 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa58() throws SailoException {    // Relaatiot: 58
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(1,1), rel2 = new Relaatio(3,3); 
    assertEquals("From: Relaatiot line: 62", 0, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 63", 1, relaatiot.getLkm()); 
    relaatiot.lisaa(rel2); assertEquals("From: Relaatiot line: 64", 2, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 65", 3, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 66", 4, relaatiot.getLkm()); 
    relaatiot.lisaa(rel1); assertEquals("From: Relaatiot line: 67", 5, relaatiot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista84 */
  @Test
  public void testPoista84() {    // Relaatiot: 84
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(1,1), rel2 = new Relaatio(2,4), rel3 = new Relaatio(7,8); 
    rel1.rekisteroi(); rel2.rekisteroi(); rel3.rekisteroi(); 
    relaatiot.lisaa(rel1); relaatiot.lisaa(rel2); relaatiot.lisaa(rel3); 
    relaatiot.poista(rel2.getTunnusNro()); assertEquals("From: Relaatiot line: 89", 2, relaatiot.getLkm()); 
    relaatiot.poista(rel1.getTunnusNro()); assertEquals("From: Relaatiot line: 90", 1, relaatiot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiId110 */
  @Test
  public void testEtsiId110() {    // Relaatiot: 110
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(1,1), rel2 = new Relaatio(2,4), rel3 = new Relaatio(3,4); 
    relaatiot.lisaa(rel1); relaatiot.lisaa(rel2); relaatiot.lisaa(rel3); 
    assertEquals("From: Relaatiot line: 114", 1, relaatiot.etsiId(rel2.getTunnusNro())); 
    assertEquals("From: Relaatiot line: 115", 2, relaatiot.etsiId(rel3.getTunnusNro())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaRelaatiot243 */
  @Test
  public void testAnnaRelaatiot243() {    // Relaatiot: 243
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(1,2); relaatiot.lisaa(rel1); 
    Relaatio rel2 = new Relaatio(2,2); relaatiot.lisaa(rel2); 
    Relaatio rel3 = new Relaatio(4,2); relaatiot.lisaa(rel3); 
    Relaatio rel4 = new Relaatio(1,1); relaatiot.lisaa(rel4); 
    Relaatio rel5 = new Relaatio(2,4); relaatiot.lisaa(rel5); 
    Relaatio rel6 = new Relaatio(1,2); relaatiot.lisaa(rel6); 
    List<Relaatio> loytyneet; 
    loytyneet = relaatiot.annaRelaatiot(3); 
    assertEquals("From: Relaatiot line: 256", 0, loytyneet.size()); 
    loytyneet = relaatiot.annaRelaatiot(2); 
    assertEquals("From: Relaatiot line: 258", 4, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 259", true, loytyneet.get(0) == rel1); 
    assertEquals("From: Relaatiot line: 260", true, loytyneet.get(1) == rel2); 
    loytyneet = relaatiot.annaRelaatiot(4); 
    assertEquals("From: Relaatiot line: 262", 1, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 263", true, loytyneet.get(0) == rel5); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKappaleenRelaatiot282 */
  @Test
  public void testAnnaKappaleenRelaatiot282() {    // Relaatiot: 282
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(1,2); relaatiot.lisaa(rel1); 
    Relaatio rel2 = new Relaatio(2,2); relaatiot.lisaa(rel2); 
    Relaatio rel3 = new Relaatio(4,2); relaatiot.lisaa(rel3); 
    Relaatio rel4 = new Relaatio(1,1); relaatiot.lisaa(rel4); 
    Relaatio rel5 = new Relaatio(2,4); relaatiot.lisaa(rel5); 
    Relaatio rel6 = new Relaatio(1,2); relaatiot.lisaa(rel6); 
    List<Relaatio> loytyneet; 
    loytyneet = relaatiot.annaKappaleenRelaatiot(5); 
    assertEquals("From: Relaatiot line: 295", 0, loytyneet.size()); 
    loytyneet = relaatiot.annaKappaleenRelaatiot(2); 
    assertEquals("From: Relaatiot line: 297", 2, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 298", true, loytyneet.get(0) == rel2); 
    assertEquals("From: Relaatiot line: 299", true, loytyneet.get(1) == rel5); 
    loytyneet = relaatiot.annaKappaleenRelaatiot(4); 
    assertEquals("From: Relaatiot line: 301", 1, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 302", true, loytyneet.get(0) == rel3); 
  } // Generated by ComTest END
}