package music2.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.14 16:17:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RelaatiotTest {



  // Generated by ComTest BEGIN
  /** testAnnaRelaatiot173 */
  @Test
  public void testAnnaRelaatiot173() {    // Relaatiot: 173
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(1,2); relaatiot.lisaa(rel1); 
    Relaatio rel2 = new Relaatio(2,2); relaatiot.lisaa(rel2); 
    Relaatio rel3 = new Relaatio(4,2); relaatiot.lisaa(rel3); 
    Relaatio rel4 = new Relaatio(1,1); relaatiot.lisaa(rel4); 
    Relaatio rel5 = new Relaatio(2,4); relaatiot.lisaa(rel5); 
    Relaatio rel6 = new Relaatio(1,2); relaatiot.lisaa(rel6); 
    List<Relaatio> loytyneet; 
    loytyneet = relaatiot.annaRelaatiot(3); 
    assertEquals("From: Relaatiot line: 186", 0, loytyneet.size()); 
    loytyneet = relaatiot.annaRelaatiot(2); 
    assertEquals("From: Relaatiot line: 188", 4, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 189", true, loytyneet.get(0) == rel1); 
    assertEquals("From: Relaatiot line: 190", true, loytyneet.get(1) == rel2); 
    loytyneet = relaatiot.annaRelaatiot(4); 
    assertEquals("From: Relaatiot line: 192", 1, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 193", true, loytyneet.get(0) == rel5); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKappaleenRelaatiot210 */
  @Test
  public void testAnnaKappaleenRelaatiot210() {    // Relaatiot: 210
    Relaatiot relaatiot = new Relaatiot(); 
    Relaatio rel1 = new Relaatio(1,2); relaatiot.lisaa(rel1); 
    Relaatio rel2 = new Relaatio(2,2); relaatiot.lisaa(rel2); 
    Relaatio rel3 = new Relaatio(4,2); relaatiot.lisaa(rel3); 
    Relaatio rel4 = new Relaatio(1,1); relaatiot.lisaa(rel4); 
    Relaatio rel5 = new Relaatio(2,4); relaatiot.lisaa(rel5); 
    Relaatio rel6 = new Relaatio(1,2); relaatiot.lisaa(rel6); 
    List<Relaatio> loytyneet; 
    loytyneet = relaatiot.annaKappaleenRelaatiot(5); 
    assertEquals("From: Relaatiot line: 223", 0, loytyneet.size()); 
    loytyneet = relaatiot.annaKappaleenRelaatiot(2); 
    assertEquals("From: Relaatiot line: 225", 2, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 226", true, loytyneet.get(0) == rel2); 
    assertEquals("From: Relaatiot line: 227", true, loytyneet.get(1) == rel5); 
    loytyneet = relaatiot.annaKappaleenRelaatiot(4); 
    assertEquals("From: Relaatiot line: 229", 1, loytyneet.size()); 
    assertEquals("From: Relaatiot line: 230", true, loytyneet.get(0) == rel3); 
  } // Generated by ComTest END
}