package music2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.12 14:21:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RelaatioTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi36 */
  @Test
  public void testRekisteroi36() {    // Relaatio: 36
    Relaatio rel1 = new Relaatio(1,1); 
    assertEquals("From: Relaatio line: 38", 0, rel1.getTunnusNro()); 
    rel1.rekisteroi(); 
    Relaatio rel2 = new Relaatio(2,1); 
    rel2.rekisteroi(); 
    int n1 = rel1.getTunnusNro(); 
    int n2 = rel2.getTunnusNro(); 
    assertEquals("From: Relaatio line: 44", n2-1, n1); 
  } // Generated by ComTest END
}