package music2.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.12 14:42:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SetitTest {


  // Generated by ComTest BEGIN
  /** testAnnaRelaatiot87 */
  @Test
  public void testAnnaRelaatiot87() {    // Setit: 87
    Setit setit = new Setit(); 
    Setti s1 = new Setti(); setit.lisaa(s1); 
    Setti s2 = new Setti(); setit.lisaa(s2); 
    Setti s3 = new Setti(); setit.lisaa(s3); 
    Setti s4 = new Setti(); setit.lisaa(s4); 
    Setti s5 = new Setti(); setit.lisaa(s5); 
    Setti s6 = new Setti(); setit.lisaa(s6); 
    List<Setti> loytyneet; 
    loytyneet = setit.annaSetit(); 
    assertEquals("From: Setit line: 100", 6, loytyneet.size()); 
    assertEquals("From: Setit line: 101", true, loytyneet.get(0) == s1); 
    assertEquals("From: Setit line: 102", true, loytyneet.get(1) == s2); 
  } // Generated by ComTest END
}