package music2.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.17 13:38:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SetitTest {



  // Generated by ComTest BEGIN
  /** testAnnaSetit64 */
  @Test
  public void testAnnaSetit64() {    // Setit: 64
    Setit setit = new Setit(); 
    Setti s1 = new Setti(); setit.lisaa(s1); 
    Setti s2 = new Setti(); setit.lisaa(s2); 
    Setti s3 = new Setti(); setit.lisaa(s3); 
    Setti s4 = new Setti(); setit.lisaa(s4); 
    Setti s5 = new Setti(); setit.lisaa(s5); 
    Setti s6 = new Setti(); setit.lisaa(s6); 
    List<Setti> loytyneet; 
    loytyneet = setit.annaSetit(); 
    assertEquals("From: Setit line: 77", 6, loytyneet.size()); 
    assertEquals("From: Setit line: 78", true, loytyneet.get(0) == s1); 
    assertEquals("From: Setit line: 79", true, loytyneet.get(1) == s2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta110 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta110() throws SailoException {    // Setit: 110
    Setit setit = new Setit(); 
    Setti s1 = new Setti(); s1.taytaSettiTiedoilla(); 
    Setti s2 = new Setti(); s2.taytaSettiTiedoilla(); 
    Setti s3 = new Setti(); s3.taytaSettiTiedoilla(); 
    Setti s4 = new Setti(); s4.taytaSettiTiedoilla(); 
    Setti s5 = new Setti(); s5.taytaSettiTiedoilla(); 
    String tiedNimi = "testisetit"; 
    File ftied = new File(tiedNimi + "/setit.dat"); 
    ftied.delete(); 
    try {
    setit.lueTiedostosta(tiedNimi); 
    fail("Setit: 122 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    setit.lisaa(s1); 
    setit.lisaa(s2); 
    setit.lisaa(s3); 
    setit.lisaa(s4); 
    setit.lisaa(s5); 
    setit.tallenna(tiedNimi); 
    setit = new Setit(); 
    setit.lueTiedostosta(tiedNimi); 
  } // Generated by ComTest END
}