package music2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import music2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.19 22:08:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SettiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi79 */
  @Test
  public void testRekisteroi79() {    // Setti: 79
    Setti setti1 = new Setti(); 
    assertEquals("From: Setti line: 81", 0, setti1.getTunnusNro()); 
    setti1.rekisteroi(); 
    Setti setti2 = new Setti(); 
    setti2.rekisteroi(); 
    int n1 = setti1.getTunnusNro(); 
    int n2 = setti2.getTunnusNro(); 
    assertEquals("From: Setti line: 87", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString150 */
  @Test
  public void testToString150() {    // Setti: 150
    Setti setti = new Setti(); 
    setti.parse("   2   |  Setti1"); 
    assertEquals("From: Setti line: 153", "2|Setti1", setti.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse167 */
  @Test
  public void testParse167() {    // Setti: 167
    Setti setti = new Setti(); 
    setti.parse("   2   |  Setti1"); 
    assertEquals("From: Setti line: 170", "2|Setti1", setti.toString()); 
    setti.rekisteroi(); 
    int n = setti.getTunnusNro(); 
    setti.parse(""+(n+20)); 
    setti.rekisteroi(); 
    assertEquals("From: Setti line: 176", n+20+1, setti.getTunnusNro()); 
    assertEquals("From: Setti line: 177", "" + (n+20+1) + "|Setti1", setti.toString()); 
  } // Generated by ComTest END
}